export const content = {
  name: 'Ran Wei',
  school: 'Graduate School of Education', university: 'Peking University',
  position: 'Assistant Professor', supervisor: 'Doctoral Supervisor',
  description: 'Ran Wei is an assistant professor at the Graduate School of Education, Peking University. She studies children’s language and cognitive development, future thinking, self-regulation, and learning with artificial intelligence.',
  nav: { home: 'Home', research: 'Research', publications: 'Publications', teaching: 'Teaching', about: 'About' },
  skip: 'Skip to content', mainNavigation: 'Main navigation', language: 'Language', homeLabel: 'Ran Wei home', updated: 'Updated',
  contact: 'Contact', location: 'Beijing, China',
  copy: { email: 'Copy email', copied: 'Copied', failed: 'Unable to copy. Please select and copy the text.' },
  phd: 'Ph.D. in Education', harvard: 'Harvard University', postdoc: 'Postdoctoral Research Fellow',
  hospital: 'Boston Children’s Hospital', medicalSchool: 'Harvard Medical School',
  home: {
    bio: 'Ran Wei is an Assistant Professor at Peking University Graduate School of Education. Situated at the crossroads of developmental science and educational technology, her research examines how early language and cognitive development unfolds across diverse cultures and ecologies, and how caregiver communicative input and emerging technologies shape early development. Her recent work focuses on the affordances and risks of AI in early development, AI-assisted parenting interventions, and the home-environment factors supporting language, self-regulation, and future thinking, especially in low-resource settings. She works across modalities including eye tracking, behavioral experiments, LENA, and large language model tools for analyzing parent-child interaction at scale. She aspires to translate findings into accessible, culturally sensitive knowledge for parents, educators, and the public.',
    selected: 'Selected publications', allPublications: 'All publications',
    portrait: 'Portrait of Ran Wei',
  },
  themes: [
    { title: 'Language development and parent–child interaction', description: 'Her work examines gestures, caregiver speech, and parent–child conversations in relation to children’s language and cognitive development. Cross-cultural studies focus on decontextualized language, including conversations about past and future events.', paperIds: ['publication-1', 'publication-7'] },
    { title: 'Future thinking and self-regulation', description: 'Her research examines children’s future thinking and the regulation of behavior and emotion. Current projects investigate the cognitive and neural mechanisms of self-regulation and procrastination, and approaches to family-based intervention.', paperIds: ['publication-4', 'publication-14'] },
    { title: 'Artificial intelligence and child development', description: 'Her research examines the effects of artificial intelligence (AI) support on children’s narrative skills, including whether learning transfers to new stories. Current projects also investigate generative AI in family-based interventions.', paperIds: ['publication-5'] },
  ],
  research: {
    intro: 'Her research in developmental and educational psychology includes cross-cultural studies and developmental cognitive neuroscience.',
    themes: 'Research areas', methods: 'Research methods', related: 'Related publications',
    methodsText: 'Methods include behavioral tasks, observations of parent–child interaction, eye tracking, electroencephalography (EEG), and analysis of children’s language environments using the Language Environment Analysis (LENA) system.',
    lab: 'Peking University Learning Sciences Laboratory',
  },
  publications: {
    intro: 'Journal articles and a book chapter, listed by publication year.',
    filter: 'Filter publications', search: 'Search publications', placeholder: 'Title, author, or journal', year: 'Year', allYears: 'All years', reset: 'Reset',
    count: 'publications', key: '+ identifies coauthors who are postdoctoral fellows, students, or research assistants. * indicates shared first or senior authorship, as specified below each publication.',
    empty: 'No publications match your search. Try another term or reset the filters.', book: 'Book chapter', resources: 'Data & analysis code',
    area: 'Research area', allAreas: 'All areas', cite: 'Cite', copyCitation: 'Copy citation', bibtex: 'Download BibTeX',
    areas: { language: 'Language development', interaction: 'Parenting and interaction', regulation: 'Self-regulation', cognition: 'Cognitive development', ai: 'AI and learning' },
  },
  teaching: {
    intro: 'Courses taught at the Graduate School of Education, Peking University.', courses: 'Courses',
    inquiries: 'Course inquiries', course1: 'Psychological Development and Education', course2: 'Marriage, Family, and Psychological Development', spring2024: 'Spring 2024–present', spring2026: 'Spring 2026–present',
  },
  about: {
    title: 'About Ran Wei',
    appointments: 'Academic appointments', education: 'Education', recognition: 'Honors and awards', service: 'Academic service', talks: 'Invited talks', present: '2023–present',
    postdocLocation: 'Brookline, Massachusetts, USA · Supervisor: Charles A. Nelson',
    phdDetail: 'Concentration: Human Development, Learning and Teaching', secondary: 'Secondary field: Mind, Brain, and Behavior — Language Acquisition',
    phdSupervisor: 'Supervisor: Meredith Rowe, Paul Harris, and Catherine Snow',
    masters: 'Ed.M. in Language and Literacy', harvardGse: 'Harvard Graduate School of Education',
    bachelor: 'B.A. in English Language and Literature', tsinghua: 'Tsinghua University',
    awards: ['Ng Teng Fong Sino Early Career Award', 'Society for Research in Child Development Early Career Travel Award', 'Harvard Graduate School of Arts and Sciences Doctoral Fellowship', 'Marco Polo Fellowship, Harvard University'],
    fellow: 'Child Development Early Career Editorial Fellow', journals: 'Journal peer review', otherReview: 'Conference and award review', conferences: 'Conferences', fellowships: 'Awards and fellowships',
    facultyPage: 'Peking University faculty profile',
  },
};
